"""updater_tables

Revision ID: 5f53ee84737b
Revises: 
Create Date: 2026-08-04 12:06:42.717616
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = '5f53ee84737b'
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_countries_code'), 'tax_countries', ['code'], unique=True)
    op.create_table('tax_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_sources_country_code'), 'tax_sources', ['country_code'], unique=False)
    op.create_table('tax_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_rules_updated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_rule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('version_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['tax_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rule_versions_jurisdiction'), 'tax_rule_versions', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_tax_rule_versions_tax_year'), 'tax_rule_versions', ['tax_year'], unique=False)
    op.create_index(op.f('ix_tax_rule_versions_version_hash'), 'tax_rule_versions', ['version_hash'], unique=True)
    op.create_table('tax_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['tax_countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code', name='uix_country_state_code')
    )
    op.create_index(op.f('ix_tax_states_code'), 'tax_states', ['code'], unique=False)
    op.create_table('tax_update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['tax_updates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['tax_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['tax_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_cities_name'), 'tax_cities', ['name'], unique=False)
    op.create_table('tax_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['tax_rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_rules')
    op.drop_index(op.f('ix_tax_cities_name'), table_name='tax_cities')
    op.drop_table('tax_cities')
    op.drop_table('tax_update_logs')
    op.drop_index(op.f('ix_tax_states_code'), table_name='tax_states')
    op.drop_table('tax_states')
    op.drop_index(op.f('ix_tax_rule_versions_version_hash'), table_name='tax_rule_versions')
    op.drop_index(op.f('ix_tax_rule_versions_tax_year'), table_name='tax_rule_versions')
    op.drop_index(op.f('ix_tax_rule_versions_jurisdiction'), table_name='tax_rule_versions')
    op.drop_table('tax_rule_versions')
    op.drop_table('tax_updates')
    op.drop_index(op.f('ix_tax_sources_country_code'), table_name='tax_sources')
    op.drop_table('tax_sources')
    op.drop_index(op.f('ix_tax_countries_code'), table_name='tax_countries')
    op.drop_table('tax_countries')
    # ### end Alembic commands ###
