"""Add SEO models

Revision ID: ba1988fb1dd8
Revises: 5f53ee84737b
Create Date: 2026-08-04 13:54:38.771140
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = "ba1988fb1dd8"
down_revision: str | None = "5f53ee84737b"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seo_redirects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("destination_url", sa.String(length=500), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seo_redirects_source_url"), "seo_redirects", ["source_url"], unique=True
    )
    op.create_table(
        "seo_routes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("calculator_type", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=3), nullable=False),
        sa.Column("state", sa.String(length=3), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("meta_description", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.String(length=500), nullable=False),
        sa.Column("h1", sa.String(length=255), nullable=False),
        sa.Column("content_paragraphs", sa.JSON(), nullable=False),
        sa.Column("faq_schema", sa.JSON(), nullable=True),
        sa.Column("software_schema", sa.JSON(), nullable=True),
        sa.Column("breadcrumb_schema", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_seo_location", "seo_routes", ["country", "state", "city"], unique=False)
    op.create_index(
        op.f("ix_seo_routes_calculator_type"), "seo_routes", ["calculator_type"], unique=False
    )
    op.create_index(op.f("ix_seo_routes_city"), "seo_routes", ["city"], unique=False)
    op.create_index(op.f("ix_seo_routes_country"), "seo_routes", ["country"], unique=False)
    op.create_index(op.f("ix_seo_routes_slug"), "seo_routes", ["slug"], unique=True)
    op.create_index(op.f("ix_seo_routes_state"), "seo_routes", ["state"], unique=False)
    op.create_index(op.f("ix_seo_routes_tax_year"), "seo_routes", ["tax_year"], unique=False)
    op.create_table(
        "seo_internal_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_route_id", sa.Integer(), nullable=False),
        sa.Column("destination_slug", sa.String(length=255), nullable=False),
        sa.Column("link_text", sa.String(length=255), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["source_route_id"], ["seo_routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seo_internal_links_source_route_id"),
        "seo_internal_links",
        ["source_route_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_seo_internal_links_source_route_id"), table_name="seo_internal_links")
    op.drop_table("seo_internal_links")
    op.drop_index(op.f("ix_seo_routes_tax_year"), table_name="seo_routes")
    op.drop_index(op.f("ix_seo_routes_state"), table_name="seo_routes")
    op.drop_index(op.f("ix_seo_routes_slug"), table_name="seo_routes")
    op.drop_index(op.f("ix_seo_routes_country"), table_name="seo_routes")
    op.drop_index(op.f("ix_seo_routes_city"), table_name="seo_routes")
    op.drop_index(op.f("ix_seo_routes_calculator_type"), table_name="seo_routes")
    op.drop_index("idx_seo_location", table_name="seo_routes")
    op.drop_table("seo_routes")
    op.drop_index(op.f("ix_seo_redirects_source_url"), table_name="seo_redirects")
    op.drop_table("seo_redirects")
    # ### end Alembic commands ###
