"""add_taxpayer_calculations_and_compliance_models

Revision ID: d9a4e0a12a97
Revises: 431f0eaf8bf7
Create Date: 2026-08-24 13:22:38.870136
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = "d9a4e0a12a97"
down_revision: str | None = "431f0eaf8bf7"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taxpayer_profiles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("taxpayer_name", sa.String(length=255), nullable=False),
        sa.Column("pan_encrypted", sa.String(length=512), nullable=True),
        sa.Column("pan_masked", sa.String(length=32), nullable=True),
        sa.Column("gstin", sa.String(length=15), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("residential_status", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_taxpayer_profiles_organization_id"),
        "taxpayer_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_taxpayer_profiles_user_id"), "taxpayer_profiles", ["user_id"], unique=False
    )
    op.create_table(
        "compliance_tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("taxpayer_profile_id", sa.String(length=64), nullable=True),
        sa.Column("obligation_id", sa.String(length=128), nullable=False),
        sa.Column("obligation_name", sa.String(length=255), nullable=False),
        sa.Column("tax_family", sa.String(length=64), nullable=False),
        sa.Column("due_date", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["taxpayer_profile_id"], ["taxpayer_profiles.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_compliance_tasks_organization_id"),
        "compliance_tasks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_compliance_tasks_user_id"), "compliance_tasks", ["user_id"], unique=False
    )
    op.create_table(
        "saved_calculations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("taxpayer_profile_id", sa.String(length=64), nullable=True),
        sa.Column("tool_id", sa.String(length=128), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("financial_year", sa.String(length=16), nullable=False),
        sa.Column("assessment_year", sa.String(length=16), nullable=True),
        sa.Column("rule_version", sa.String(length=64), nullable=False),
        sa.Column("inputs_json", sa.JSON(), nullable=False),
        sa.Column("results_json", sa.JSON(), nullable=False),
        sa.Column("trace_steps_json", sa.JSON(), nullable=False),
        sa.Column("total_tax_payable", sa.Float(), nullable=False),
        sa.Column("effective_tax_rate", sa.Float(), nullable=False),
        sa.Column("is_favourite", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["taxpayer_profile_id"], ["taxpayer_profiles.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_calculations_organization_id"),
        "saved_calculations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_saved_calculations_tool_id"), "saved_calculations", ["tool_id"], unique=False
    )
    op.create_index(
        op.f("ix_saved_calculations_user_id"), "saved_calculations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_calculations_user_id"), table_name="saved_calculations")
    op.drop_index(op.f("ix_saved_calculations_tool_id"), table_name="saved_calculations")
    op.drop_index(op.f("ix_saved_calculations_organization_id"), table_name="saved_calculations")
    op.drop_table("saved_calculations")
    op.drop_index(op.f("ix_compliance_tasks_user_id"), table_name="compliance_tasks")
    op.drop_index(op.f("ix_compliance_tasks_organization_id"), table_name="compliance_tasks")
    op.drop_table("compliance_tasks")
    op.drop_index(op.f("ix_taxpayer_profiles_user_id"), table_name="taxpayer_profiles")
    op.drop_index(op.f("ix_taxpayer_profiles_organization_id"), table_name="taxpayer_profiles")
    op.drop_table("taxpayer_profiles")
    # ### end Alembic commands ###
