"""Markdown document generator.

Generates a clean Markdown report suitable for embedding in
documentation, README files, or rendering in any Markdown viewer.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from taxos.domain.calculators.schema import CalculatorConfig
from taxos.domain.documents.schema import ReportTemplateConfig


def _fmt(val: Any, fmt: str, sym: str) -> str:
    """Format a value based on its format type."""
    if val is None:
        return "—"
    try:
        fval = float(val)
    except (TypeError, ValueError):
        return str(val)
    if fmt == "currency":
        return f"{sym}{fval:,.2f}"
    if fmt == "percentage":
        return f"{fval:.2f}%"
    return f"{fval:,.2f}"


class MarkdownDocumentGenerator:
    """Generates Markdown exports from any calculator's results."""

    def generate(
        self,
        calculator_config: CalculatorConfig,
        results: dict[str, Any],
        template: ReportTemplateConfig,
        inputs_data: dict[str, Any] | None = None,
    ) -> bytes:
        """Generate a Markdown byte string."""
        sym = template.locale.currency_symbol
        now = datetime.now(timezone.utc).strftime(template.locale.date_format)
        lines: list[str] = []

        lines.append(f"# {calculator_config.title}")
        lines.append("")
        lines.append(f"> {calculator_config.description}")
        lines.append("")
        lines.append(f"*Generated by {template.branding.company_name} on {now}*")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        for formula in calculator_config.formulas:
            if formula.is_result:
                val = _fmt(results.get(formula.id), formula.format, sym)
                label = formula.label or formula.id
                lines.append(f"- **{label}**: {val}")
        lines.append("")

        # Inputs
        if inputs_data:
            lines.append("## Inputs")
            lines.append("")
            lines.append("| Field | Value |")
            lines.append("|-------|-------|")
            for inp in calculator_config.inputs:
                val = inputs_data.get(inp.id, inp.default)
                lines.append(f"| {inp.label} | {val} |")
            lines.append("")

        # Breakdown
        lines.append("## Detailed Breakdown")
        lines.append("")
        lines.append("| Item | Value |")
        lines.append("|------|-------|")
        for formula in calculator_config.formulas:
            val = _fmt(results.get(formula.id), formula.format, sym)
            label = formula.label or formula.id
            lines.append(f"| {label} | {val} |")
        lines.append("")

        # Disclaimer
        for section in template.sections:
            if section.type == "disclaimer" and section.content:
                lines.append("---")
                lines.append("")
                lines.append(f"*{section.content}*")
                lines.append("")

        return "\n".join(lines).encode("utf-8")
