"""Configuration schemas for the Universal Document Engine.

Every report template is defined by a JSON configuration file.
No hardcoded layouts — everything is driven by these schemas.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# ── Branding ─────────────────────────────────────────────────────


class BrandingConfig(BaseModel):
    """Corporate branding applied to generated documents."""

    company_name: str = "TaxOS"
    company_address: str = ""
    logo_path: str | None = None
    primary_color: str = "#1a56db"
    secondary_color: str = "#6b7280"
    accent_color: str = "#059669"
    font_family: str = "helvetica"
    header_text: str = ""
    footer_text: str = "Generated by TaxOS — taxos.io"


# ── Locale ───────────────────────────────────────────────────────


class LocaleConfig(BaseModel):
    """Localization settings for a report."""

    language: str = "en"
    currency_symbol: str = "$"
    currency_code: str = "USD"
    date_format: str = "%Y-%m-%d"
    number_format: str = "#,##0.00"
    rtl: bool = False


# ── Charts ───────────────────────────────────────────────────────


class ReportChartConfig(BaseModel):
    """Defines a chart to embed in the document."""

    id: str
    type: Literal["pie", "bar", "line", "area", "stacked_bar"] = "bar"
    title: str = ""
    data_sources: list[str] = Field(default_factory=list)
    colors: list[str] | None = None
    width: int = 600
    height: int = 400


# ── Sections ─────────────────────────────────────────────────────


class SectionConfig(BaseModel):
    """A single configurable section of a report.

    Sections are rendered in order. Each section type has its own
    rendering logic but the data it displays is driven entirely by
    the calculator results and configuration.
    """

    id: str
    type: Literal[
        "cover_page",
        "summary_cards",
        "data_table",
        "breakdown_table",
        "chart",
        "inputs_table",
        "text_block",
        "key_value_list",
        "comparison_table",
        "disclaimer",
        "notes",
        "page_break",
    ]
    title: str = ""
    subtitle: str = ""
    visible: bool = True
    # For data_table / breakdown_table — which result keys to include
    data_keys: list[str] = Field(default_factory=list)
    # For chart sections
    chart: ReportChartConfig | None = None
    # For text_block / disclaimer / notes
    content: str = ""
    # Conditional visibility expression (e.g. "total_tax > 0")
    condition: str | None = None


# ── Root Template ────────────────────────────────────────────────


class ReportTemplateConfig(BaseModel):
    """The root configuration for a report template.

    Stored as JSON in ``rules/report_templates/{id}.json``.
    Any calculator can reference a template by its ``id``.
    """

    id: str = Field(pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$", min_length=2, max_length=100)
    name: str
    description: str = ""
    version: str = "1.0"

    # Page settings
    orientation: Literal["portrait", "landscape"] = "portrait"
    page_size: Literal["A4", "letter", "legal"] = "A4"

    # Style
    template_style: Literal[
        "minimal",
        "corporate",
        "government",
        "detailed",
        "executive",
        "dark",
        "light",
        "print_friendly",
    ] = "corporate"

    branding: BrandingConfig = Field(default_factory=BrandingConfig)
    locale: LocaleConfig = Field(default_factory=LocaleConfig)

    # Watermark
    watermark_text: str | None = None

    # Ordered list of sections to render
    sections: list[SectionConfig] = Field(default_factory=list)

    # Which export formats this template supports
    supported_formats: list[str] = Field(
        default_factory=lambda: ["pdf", "excel", "csv", "json", "html", "xml", "markdown", "text"]
    )

    # QR code — link target pattern (e.g. "https://taxos.io/reports/{report_id}")
    qr_code_url_pattern: str | None = None
