"""Canonical 1-845 TaxOS master-plan tool names.

This file is derived from the product plan and is metadata-only.
Implementation status is resolved by the runtime registry.
"""

MASTER_PLAN_TOOL_NAMES: dict[int, str] = {
    1: "Income Tax Calculator",
    2: "New Tax Regime Calculator",
    3: "Old Tax Regime Calculator",
    4: "Old vs New Regime Comparator",
    5: "Tax Regime Recommendation Calculator",
    6: "Taxable Income Calculator",
    7: "Gross Total Income Calculator",
    8: "Effective Tax Rate Calculator",
    9: "Marginal Tax Rate Calculator",
    10: "Tax Liability Calculator",
    11: "Rebate Calculator",
    12: "Surcharge Calculator",
    13: "Marginal Relief Calculator",
    14: "Health & Education Cess Calculator",
    15: "Net Tax Payable Calculator",
    16: "Tax Refund Estimator",
    17: "Tax Shortfall Calculator",
    18: "Tax Savings Calculator",
    19: "Tax Planning Simulator",
    20: "Multi-Income Tax Calculator",
    21: "Salary Tax Calculator",
    22: "CTC to Tax Calculator",
    23: "CTC to Take-Home Calculator",
    24: "Gross Salary Calculator",
    25: "Net Salary Calculator",
    26: "Taxable Salary Calculator",
    27: "Salary Structure Analyzer",
    28: "Basic Salary Tax Analyzer",
    29: "HRA Calculator",
    30: "HRA Exemption Calculator",
    31: "LTA Calculator",
    32: "Standard Deduction Calculator",
    33: "Bonus Tax Calculator",
    34: "Incentive Tax Calculator",
    35: "Arrears Tax Calculator",
    36: "Relief under Section 89 Calculator",
    37: "Gratuity Tax Calculator",
    38: "Leave Encashment Tax Calculator",
    39: "Pension Tax Calculator",
    40: "Family Pension Tax Calculator",
    41: "Employer NPS Contribution Calculator",
    42: "Employee NPS Tax Benefit Calculator",
    43: "Perquisite Tax Calculator",
    44: "Company Car Perquisite Calculator",
    45: "Rent-Free Accommodation Calculator",
    46: "ESOP Tax Calculator",
    47: "RSU Tax Calculator",
    48: "Salary TDS Calculator",
    49: "Monthly TDS Planner",
    50: "Payroll Tax Analyzer",
    51: "Section 80C Calculator",
    52: "Section 80CCD Calculator",
    53: "Section 80D Calculator",
    54: "Section 80DD Calculator",
    55: "Section 80DDB Calculator",
    56: "Section 80E Calculator",
    57: "Section 80G Calculator",
    58: "Section 80GG Calculator",
    59: "Section 80TTA Calculator",
    60: "Section 80TTB Calculator",
    61: "Deduction Eligibility Checker",
    62: "Deduction Limit Checker",
    63: "Tax Saving Investment Calculator",
    64: "Deduction Optimizer",
    65: "Deduction Comparison Tool",
    66: "Missing Deduction Detector",
    67: "Tax Saving Opportunity Finder",
    68: "Deduction Documentation Checklist",
    69: "Deduction Proof Validator",
    70: "Deduction Summary Generator",
    71: "Capital Gains Calculator",
    72: "Short-Term Capital Gains Calculator",
    73: "Long-Term Capital Gains Calculator",
    74: "Equity Capital Gains Calculator",
    75: "Mutual Fund Capital Gains Calculator",
    76: "Debt Fund Tax Calculator",
    77: "Property Capital Gains Calculator",
    78: "Gold Capital Gains Calculator",
    79: "Bond Capital Gains Calculator",
    80: "ETF Capital Gains Calculator",
    81: "Foreign Share Capital Gains Calculator",
    82: "ESOP Capital Gains Calculator",
    83: "RSU Capital Gains Calculator",
    84: "Unlisted Share Gains Calculator",
    85: "Cost of Acquisition Calculator",
    86: "Indexed Cost Calculator",
    87: "Improvement Cost Calculator",
    88: "Capital Loss Calculator",
    89: "Capital Loss Set-Off Tool",
    90: "Capital Loss Carry-Forward Tool",
    91: "Capital Gains Tax Harvesting Calculator",
    92: "Transaction-Wise Gains Calculator",
    93: "Broker Trade Capital Gains Analyzer",
    94: "FIFO Capital Gains Calculator",
    95: "Investment Tax Lot Analyzer",
    96: "Corporate Action Cost Adjuster",
    97: "Bonus Share Cost Calculator",
    98: "Rights Issue Tax Calculator",
    99: "Capital Gains Statement Generator",
    100: "Capital Gains Audit Tool",
    101: "STT Calculator",
    102: "Dividend Tax Calculator",
    103: "Interest Income Tax Calculator",
    104: "FD Tax Calculator",
    105: "RD Tax Calculator",
    106: "Bond Interest Tax Calculator",
    107: "Sovereign Gold Bond Tax Analyzer",
    108: "Mutual Fund Tax Analyzer",
    109: "Equity Tax Analyzer",
    110: "Futures Tax Analyzer",
    111: "Options Tax Analyzer",
    112: "Intraday Trading Tax Analyzer",
    113: "F&O Turnover Calculator",
    114: "Trading Business Income Calculator",
    115: "Trading Expense Deduction Analyzer",
    116: "Speculative Income Calculator",
    117: "Non-Speculative Income Calculator",
    118: "Securities Tax Summary",
    119: "Investor Tax Dashboard",
    120: "Trader Tax Dashboard",
    121: "Crypto Tax Calculator",
    122: "VDA Tax Calculator",
    123: "Crypto Profit Calculator",
    124: "Crypto Loss Calculator",
    125: "Crypto Transaction Analyzer",
    126: "Crypto TDS Calculator",
    127: "Crypto FIFO Calculator",
    128: "Crypto Wallet Transaction Parser",
    129: "Exchange Transaction Importer",
    130: "Crypto Cost Basis Calculator",
    131: "Coin-to-Coin Transaction Analyzer",
    132: "Crypto Tax Ledger",
    133: "Crypto Tax Statement Generator",
    134: "VDA Compliance Checker",
    135: "Crypto Tax Audit Report",
    136: "House Property Income Calculator",
    137: "Rental Income Tax Calculator",
    138: "Self-Occupied Property Calculator",
    139: "Let-Out Property Calculator",
    140: "Home Loan Interest Deduction Calculator",
    141: "Municipal Tax Deduction Calculator",
    142: "Net Annual Value Calculator",
    143: "Gross Annual Value Calculator",
    144: "Standard Property Deduction Calculator",
    145: "Property Loss Calculator",
    146: "Multiple Property Tax Calculator",
    147: "Co-Owned Property Calculator",
    148: "Property Income Statement Generator",
    149: "Rental Property Tax Analyzer",
    150: "Property Tax Planning Simulator",
    151: "Business Income Tax Calculator",
    152: "Professional Income Tax Calculator",
    153: "Profit Tax Calculator",
    154: "Taxable Business Profit Calculator",
    155: "Allowable Expense Checker",
    156: "Disallowable Expense Checker",
    157: "Business Expense Classifier",
    158: "Depreciation Calculator",
    159: "Block of Assets Calculator",
    160: "Written Down Value Calculator",
    161: "Tax Depreciation Schedule Generator",
    162: "Business Loss Calculator",
    163: "Loss Carry-Forward Calculator",
    164: "Loss Set-Off Analyzer",
    165: "Partner Remuneration Calculator",
    166: "Partner Interest Calculator",
    167: "Business Tax Provision Calculator",
    168: "Business Tax Reconciliation",
    169: "Tax Audit Readiness Checker",
    170: "Business Income Tax Report",
    171: "Presumptive Tax Calculator",
    172: "Section 44AD Calculator",
    173: "Section 44ADA Calculator",
    174: "Section 44AE Calculator",
    175: "Presumptive Eligibility Checker",
    176: "Presumptive vs Normal Tax Comparator",
    177: "Presumptive Turnover Analyzer",
    178: "Presumptive Profit Calculator",
    179: "Books Requirement Checker",
    180: "Tax Audit Requirement Checker",
    181: "Advance Tax Calculator",
    182: "Quarterly Advance Tax Calculator",
    183: "Advance Tax Installment Planner",
    184: "Advance Tax Shortfall Calculator",
    185: "Self-Assessment Tax Calculator",
    186: "Tax Payment Planner",
    187: "Tax Liability Forecast",
    188: "Tax Due Date Calculator",
    189: "Advance Tax Interest Estimator",
    190: "Tax Payment Schedule Generator",
    191: "Section 234A Interest Calculator",
    192: "Section 234B Interest Calculator",
    193: "Section 234C Interest Calculator",
    194: "Late Filing Fee Calculator",
    195: "Tax Interest Calculator",
    196: "Delay Period Calculator",
    197: "Tax Default Cost Calculator",
    198: "Late Payment Cost Calculator",
    199: "Interest Reconciliation Tool",
    200: "Tax Delay Report",
    201: "TDS Calculator",
    202: "Salary TDS Calculator",
    203: "Contractor TDS Calculator",
    204: "Professional Fee TDS Calculator",
    205: "Rent TDS Calculator",
    206: "Interest TDS Calculator",
    207: "Commission TDS Calculator",
    208: "Dividend TDS Calculator",
    209: "Property Purchase TDS Calculator",
    210: "Non-Resident TDS Calculator",
    211: "TDS Section Finder",
    212: "TDS Rate Finder",
    213: "TDS Threshold Checker",
    214: "TDS Due Date Calculator",
    215: "TDS Interest Calculator",
    216: "TDS Late Fee Calculator",
    217: "TDS Challan Validator",
    218: "TDS Deduction Register",
    219: "TDS Reconciliation",
    220: "TDS Compliance Dashboard",
    221: "TCS Calculator",
    222: "TCS Rate Finder",
    223: "TCS Applicability Checker",
    224: "TCS Threshold Checker",
    225: "Foreign Remittance TCS Calculator",
    226: "Overseas Tour TCS Calculator",
    227: "Sale of Goods TCS Calculator",
    228: "TCS Due Date Calculator",
    229: "TCS Interest Calculator",
    230: "TCS Compliance Report",
    231: "Form 16 Analyzer",
    232: "Form 16 Tax Extractor",
    233: "Form 16 Salary Reconciler",
    234: "Form 16 vs Payslip Comparator",
    235: "Form 16 vs ITR Comparator",
    236: "Form 16A Analyzer",
    237: "AIS Analyzer",
    238: "TIS Analyzer",
    239: "Form 26AS Analyzer",
    240: "AIS vs 26AS Reconciliation",
    241: "AIS vs Bank Statement Comparator",
    242: "AIS vs Broker Statement Comparator",
    243: "TDS Credit Reconciliation",
    244: "Missing TDS Credit Finder",
    245: "Income Mismatch Detector",
    246: "High-Value Transaction Analyzer",
    247: "Tax Information Consolidator",
    248: "Annual Tax Statement Generator",
    249: "ITR Data Preparation Tool",
    250: "Tax Reconciliation Report",
    251: "ITR Form Selector",
    252: "ITR-1 Eligibility Checker",
    253: "ITR-2 Eligibility Checker",
    254: "ITR-3 Eligibility Checker",
    255: "ITR-4 Eligibility Checker",
    256: "ITR Filing Readiness Checker",
    257: "Income Source Classifier",
    258: "ITR Data Validator",
    259: "ITR JSON Analyzer",
    260: "ITR JSON Validator",
    261: "ITR Data Completeness Checker",
    262: "Missing Schedule Detector",
    263: "ITR Tax Reconciliation",
    264: "ITR Refund Estimator",
    265: "ITR Defect Risk Checker",
    266: "Revised Return Eligibility Checker",
    267: "Updated Return Eligibility Checker",
    268: "ITR Filing Checklist Generator",
    269: "ITR Summary Generator",
    270: "ITR Audit Report",
    271: "GST Calculator",
    272: "Inclusive GST Calculator",
    273: "Exclusive GST Calculator",
    274: "Reverse GST Calculator",
    275: "CGST Calculator",
    276: "SGST Calculator",
    277: "IGST Calculator",
    278: "UTGST Calculator",
    279: "GST Split Calculator",
    280: "GST Margin Calculator",
    281: "GST Markup Calculator",
    282: "GST Invoice Calculator",
    283: "Multi-Rate GST Calculator",
    284: "GST Taxable Value Calculator",
    285: "GST Discount Calculator",
    286: "GST Freight Calculator",
    287: "GST Round-Off Calculator",
    288: "GST Comparison Calculator",
    289: "GST Transaction Calculator",
    290: "GST Batch Calculator",
    291: "GST Registration Eligibility Checker",
    292: "GST Registration Threshold Checker",
    293: "Mandatory Registration Checker",
    294: "Voluntary Registration Analyzer",
    295: "Casual Taxpayer Checker",
    296: "Non-Resident Taxpayer Checker",
    297: "GSTIN Validator",
    298: "GSTIN Format Checker",
    299: "GST State Code Finder",
    300: "GST Registration Document Checklist",
    301: "HSN Code Search",
    302: "SAC Code Search",
    303: "HSN Description Search",
    304: "HSN Rate Finder",
    305: "SAC Rate Finder",
    306: "Product-to-HSN Classifier",
    307: "Service-to-SAC Classifier",
    308: "HSN Validation Tool",
    309: "HSN Invoice Checker",
    310: "HSN Master Database Tool",
    311: "GST Invoice Generator",
    312: "GST Invoice Validator",
    313: "Tax Invoice Checker",
    314: "Bill of Supply Checker",
    315: "Credit Note Generator",
    316: "Debit Note Generator",
    317: "GST Invoice Number Validator",
    318: "Mandatory Invoice Field Checker",
    319: "GST Invoice Tax Calculator",
    320: "Invoice Duplicate Finder",
    321: "Invoice Sequence Checker",
    322: "Invoice Tax Mismatch Detector",
    323: "Invoice GSTIN Validator",
    324: "Invoice HSN Validator",
    325: "GST Invoice Audit",
    326: "GSTR-1 Analyzer",
    327: "GSTR-1 Validator",
    328: "GSTR-1 Reconciliation",
    329: "GSTR-3B Analyzer",
    330: "GSTR-3B Validator",
    331: "GSTR-1 vs GSTR-3B Comparator",
    332: "GSTR-2B Analyzer",
    333: "GSTR-2B Reconciliation",
    334: "GSTR-2B Purchase Matcher",
    335: "GSTR-9 Analyzer",
    336: "GSTR-9 Preparation Tool",
    337: "GSTR-9C Reconciliation",
    338: "GST Annual Return Analyzer",
    339: "GST Return Due Date Calendar",
    340: "GST Return Compliance Dashboard",
    341: "ITC Calculator",
    342: "Eligible ITC Checker",
    343: "Ineligible ITC Checker",
    344: "Blocked Credit Analyzer",
    345: "GSTR-2B ITC Matcher",
    346: "Purchase Invoice Matcher",
    347: "Vendor ITC Compliance Analyzer",
    348: "Missing ITC Finder",
    349: "Excess ITC Detector",
    350: "Duplicate ITC Detector",
    351: "ITC Reversal Calculator",
    352: "ITC Reclaim Calculator",
    353: "Rule-Based ITC Analyzer",
    354: "ITC Aging Report",
    355: "ITC Reconciliation Dashboard",
    356: "Sales vs GSTR-1 Reconciliation",
    357: "GSTR-1 vs GSTR-3B Reconciliation",
    358: "Purchases vs GSTR-2B Reconciliation",
    359: "Books vs GST Return Reconciliation",
    360: "Invoice-Level GST Matcher",
    361: "Fuzzy Invoice Matcher",
    362: "GST Amount Mismatch Finder",
    363: "GSTIN Mismatch Finder",
    364: "Tax Rate Mismatch Finder",
    365: "Missing Invoice Finder",
    366: "Duplicate Invoice Finder",
    367: "Vendor Compliance Checker",
    368: "Customer GST Reconciliation",
    369: "GST Exception Manager",
    370: "GST Reconciliation Report",
    371: "E-Invoice Eligibility Checker",
    372: "E-Invoice JSON Validator",
    373: "E-Invoice Schema Validator",
    374: "IRN Data Validator",
    375: "QR Code Data Validator",
    376: "Invoice Reference Analyzer",
    377: "E-Invoice JSON Generator",
    378: "E-Invoice Batch Validator",
    379: "E-Invoice vs Books Reconciliation",
    380: "E-Invoice vs GSTR-1 Reconciliation",
    381: "Cancelled E-Invoice Analyzer",
    382: "E-Invoice Duplicate Detector",
    383: "E-Invoice Error Explainer",
    384: "E-Invoice Compliance Dashboard",
    385: "E-Invoice Audit Report",
    386: "E-Way Bill Applicability Checker",
    387: "E-Way Bill Distance Calculator",
    388: "E-Way Bill Validity Calculator",
    389: "E-Way Bill Data Validator",
    390: "E-Way Bill Invoice Matcher",
    391: "E-Way Bill Vehicle Number Validator",
    392: "E-Way Bill Expiry Checker",
    393: "E-Way Bill Extension Planner",
    394: "E-Way Bill Reconciliation",
    395: "E-Way Bill Compliance Report",
    396: "Reverse Charge Calculator",
    397: "RCM Applicability Checker",
    398: "Composition Scheme Calculator",
    399: "Composition Eligibility Checker",
    400: "Export GST Analyzer",
    401: "LUT Eligibility Checker",
    402: "Zero-Rated Supply Checker",
    403: "SEZ Supply Analyzer",
    404: "GST Refund Calculator",
    405: "GST Refund Eligibility Checker",
    406: "Place of Supply Analyzer",
    407: "Time of Supply Analyzer",
    408: "Value of Supply Calculator",
    409: "Inter-State vs Intra-State Checker",
    410: "Branch Transfer GST Analyzer",
    411: "Customs Duty Calculator",
    412: "Basic Customs Duty Calculator",
    413: "Import IGST Calculator",
    414: "Social Welfare Surcharge Calculator",
    415: "Landed Cost Calculator",
    416: "Import Tax Calculator",
    417: "Export Duty Calculator",
    418: "Customs Valuation Calculator",
    419: "Assessable Value Calculator",
    420: "Import Cost Calculator",
    421: "Duty Drawback Calculator",
    422: "Customs Classification Helper",
    423: "Import Invoice Analyzer",
    424: "Bill of Entry Analyzer",
    425: "Customs Duty Reconciliation",
    426: "Company Tax Calculator",
    427: "Domestic Company Tax Calculator",
    428: "Corporate Tax Regime Comparator",
    429: "Corporate Surcharge Calculator",
    430: "Corporate Marginal Relief Calculator",
    431: "Corporate Tax Provision Calculator",
    432: "Deferred Tax Calculator",
    433: "Current Tax Calculator",
    434: "Effective Tax Rate Calculator",
    435: "MAT Calculator",
    436: "MAT Credit Calculator",
    437: "AMT Calculator",
    438: "Tax Loss Carry-Forward",
    439: "Deferred Tax Asset Calculator",
    440: "Deferred Tax Liability Calculator",
    441: "Partnership Firm Tax Calculator",
    442: "LLP Tax Calculator",
    443: "Partner Remuneration Calculator",
    444: "Partner Interest Calculator",
    445: "HUF Tax Calculator",
    446: "HUF Income Analyzer",
    447: "Trust Tax Calculator",
    448: "NGO Tax Analyzer",
    449: "Charitable Trust Compliance Checker",
    450: "Entity Tax Comparator",
    451: "NRI Tax Calculator",
    452: "NRI Residential Status Checker",
    453: "RNOR Status Checker",
    454: "Foreign Income Tax Analyzer",
    455: "Foreign Tax Credit Calculator",
    456: "DTAA Relief Calculator",
    457: "Treaty Rate Finder",
    458: "TDS for Non-Resident Calculator",
    459: "Foreign Salary Tax Analyzer",
    460: "Foreign Dividend Tax Analyzer",
    461: "Foreign Capital Gains Analyzer",
    462: "Double Taxation Analyzer",
    463: "Permanent Establishment Risk Questionnaire",
    464: "Transfer Pricing Documentation Checker",
    465: "Arm's-Length Analysis Workspace",
    466: "Related Party Transaction Analyzer",
    467: "Transfer Pricing Adjustment Calculator",
    468: "International Tax Calendar",
    469: "Cross-Border Tax Summary",
    470: "International Tax Report",
    471: "Tax Calendar",
    472: "Income Tax Due Date Tracker",
    473: "GST Due Date Tracker",
    474: "TDS Due Date Tracker",
    475: "TCS Due Date Tracker",
    476: "Tax Notice Tracker",
    477: "Tax Notice Analyzer",
    478: "Tax Demand Analyzer",
    479: "Tax Refund Tracker Workspace",
    480: "Compliance Risk Score",
    481: "Missing Filing Detector",
    482: "Filing Status Dashboard",
    483: "Tax Document Vault",
    484: "Tax Working Paper Generator",
    485: "Tax Audit Trail",
    486: "Tax Reconciliation Workspace",
    487: "Tax Liability Dashboard",
    488: "Tax Provision Dashboard",
    489: "Business Tax Compliance Dashboard",
    490: "CFO Tax Dashboard",
    491: "Global Income Tax Calculator",
    492: "Country Income Tax Calculator",
    493: "Tax Take-Home Calculator",
    494: "Gross-to-Net Calculator",
    495: "Marginal Tax Calculator",
    496: "Effective Tax Rate Calculator",
    497: "Progressive Tax Calculator",
    498: "Flat Tax Calculator",
    499: "Tax Allowance Calculator",
    500: "Tax Credit Calculator",
    501: "Married Tax Calculator",
    502: "Single Taxpayer Calculator",
    503: "Family Tax Calculator",
    504: "Self-Employed Tax Calculator",
    505: "Freelancer Tax Calculator",
    506: "Contractor Tax Calculator",
    507: "Remote Worker Tax Calculator",
    508: "Expat Tax Calculator",
    509: "Foreign Income Tax Calculator",
    510: "Multi-Country Income Tax Comparator",
    511: "Payroll Tax Calculator",
    512: "Employer Payroll Cost Calculator",
    513: "Employee Payroll Deduction Calculator",
    514: "Social Security Calculator",
    515: "Social Insurance Calculator",
    516: "Pension Contribution Calculator",
    517: "Employer Contribution Calculator",
    518: "Employee Contribution Calculator",
    519: "Gross-to-Net Payroll",
    520: "Net-to-Gross Payroll",
    521: "Bonus Tax Calculator",
    522: "Stock Compensation Tax Calculator",
    523: "Payroll Cost by Country",
    524: "International Payroll Comparator",
    525: "Payroll Tax Report",
    526: "Corporate Income Tax Calculator",
    527: "Corporate Tax Rate Finder",
    528: "Effective Corporate Tax Rate",
    529: "Current Tax Provision Calculator",
    530: "Deferred Tax Calculator",
    531: "Tax Loss Calculator",
    532: "Tax Loss Carry-Forward",
    533: "Tax Credit Analyzer",
    534: "Corporate Tax Comparator",
    535: "Country Corporate Tax Comparator",
    536: "Corporate Tax Forecast",
    537: "Corporate Tax Provision",
    538: "Corporate Tax Reconciliation",
    539: "Corporate Tax Dashboard",
    540: "Corporate Tax Report",
    541: "VAT Calculator",
    542: "GST Calculator",
    543: "VAT Inclusive Calculator",
    544: "VAT Exclusive Calculator",
    545: "Reverse VAT Calculator",
    546: "VAT Rate Finder",
    547: "GST Rate Finder",
    548: "VAT Registration Threshold Checker",
    549: "VAT Registration Eligibility",
    550: "VAT Number Validator",
    551: "VAT Invoice Validator",
    552: "Input VAT Calculator",
    553: "Output VAT Calculator",
    554: "VAT Return Calculator",
    555: "VAT Reconciliation",
    556: "VAT Refund Calculator",
    557: "VAT Reverse Charge Calculator",
    558: "Cross-Border VAT Analyzer",
    559: "Place-of-Supply Analyzer",
    560: "VAT Compliance Dashboard",
    561: "US Sales Tax Calculator",
    562: "State Sales Tax Calculator",
    563: "Local Sales Tax Calculator",
    564: "Combined Sales Tax Calculator",
    565: "Sales Tax Nexus Checker",
    566: "Economic Nexus Threshold Checker",
    567: "Physical Nexus Checker",
    568: "Marketplace Facilitator Analyzer",
    569: "Sales Tax Exemption Checker",
    570: "Resale Certificate Checker",
    571: "Taxability Classifier",
    572: "State Registration Tracker",
    573: "Sales Tax Filing Calendar",
    574: "Sales Tax Reconciliation",
    575: "US Sales Tax Dashboard",
    576: "EU VAT Calculator",
    577: "EU VAT Rate Finder",
    578: "EU VAT Number Validator",
    579: "Intra-EU Supply Analyzer",
    580: "Reverse Charge Checker",
    581: "OSS Calculator",
    582: "IOSS Calculator",
    583: "Distance Selling Analyzer",
    584: "EU Digital Service VAT Tool",
    585: "VAT Place-of-Supply Tool",
    586: "EU VAT Invoice Checker",
    587: "Cross-Border VAT Analyzer",
    588: "EU VAT Return Workspace",
    589: "EU VAT Compliance Dashboard",
    590: "EU VAT Report",
    591: "UK VAT Calculator",
    592: "VAT Registration Threshold Checker",
    593: "VAT Scheme Comparator",
    594: "Flat Rate Scheme Calculator",
    595: "VAT Invoice Validator",
    596: "Input/Output VAT Analyzer",
    597: "Reverse Charge Analyzer",
    598: "Making Tax Digital Readiness Checker",
    599: "UK VAT Reconciliation",
    600: "UK VAT Dashboard",
    601: "GST Calculator",
    602: "HST Calculator",
    603: "GST/HST Calculator",
    604: "PST Calculator",
    605: "QST Calculator",
    606: "Provincial Tax Comparator",
    607: "Canadian Income Tax Calculator",
    608: "Payroll Deduction Calculator",
    609: "Corporate Tax Calculator",
    610: "Canadian Tax Dashboard",
    611: "Australian Income Tax Calculator",
    612: "Australian GST Calculator",
    613: "PAYG Calculator",
    614: "Superannuation Calculator",
    615: "Capital Gains Tax Calculator",
    616: "Business Tax Calculator",
    617: "GST Registration Checker",
    618: "BAS Calculator",
    619: "Payroll Tax Calculator",
    620: "Australia Tax Dashboard",
    621: "UAE VAT Calculator",
    622: "UAE Corporate Tax Calculator",
    623: "UAE VAT Registration Checker",
    624: "UAE VAT Invoice Validator",
    625: "UAE Corporate Tax Analyzer",
    626: "UAE Free Zone Tax Analyzer",
    627: "Saudi VAT Calculator",
    628: "Saudi E-Invoice Validator",
    629: "GCC VAT Comparator",
    630: "GCC Tax Dashboard",
    631: "Singapore GST Calculator",
    632: "Singapore Income Tax Calculator",
    633: "Singapore Corporate Tax Calculator",
    634: "New Zealand GST Calculator",
    635: "New Zealand Income Tax Calculator",
    636: "Japan Consumption Tax Calculator",
    637: "Japan Income Tax Calculator",
    638: "South Africa VAT Calculator",
    639: "South Africa Income Tax Calculator",
    640: "Asia-Pacific Tax Comparator",
    641: "Tax Residency Checker",
    642: "Dual Residency Analyzer",
    643: "Treaty Eligibility Checker",
    644: "Treaty Rate Finder",
    645: "Withholding Tax Calculator",
    646: "Cross-Border Withholding Calculator",
    647: "Dividend Withholding Calculator",
    648: "Interest Withholding Calculator",
    649: "Royalty Withholding Calculator",
    650: "Service Fee Withholding Calculator",
    651: "Foreign Tax Credit Calculator",
    652: "Double Tax Relief Calculator",
    653: "Permanent Establishment Questionnaire",
    654: "Source-of-Income Analyzer",
    655: "Cross-Border Employment Tax Analyzer",
    656: "Remote Worker Tax Analyzer",
    657: "Digital Nomad Tax Analyzer",
    658: "Expat Tax Comparator",
    659: "International Contractor Tax Analyzer",
    660: "Cross-Border Tax Report",
    661: "Transfer Pricing Analyzer",
    662: "Related Party Transaction Analyzer",
    663: "Arm's-Length Price Calculator",
    664: "Comparable Transaction Analyzer",
    665: "Comparable Company Analyzer",
    666: "Interquartile Range Calculator",
    667: "Transfer Pricing Adjustment Calculator",
    668: "TNMM Calculator",
    669: "CUP Analysis Tool",
    670: "Cost Plus Analysis",
    671: "Resale Price Analysis",
    672: "Profit Split Calculator",
    673: "Transfer Pricing Risk Score",
    674: "Master File Checklist",
    675: "Local File Checklist",
    676: "Country-by-Country Data Analyzer",
    677: "Related Party Disclosure Generator",
    678: "Transfer Pricing Documentation Builder",
    679: "Transfer Pricing Audit Workspace",
    680: "Transfer Pricing Report",
    681: "Pillar Two Applicability Checker",
    682: "Global Minimum Tax Calculator",
    683: "Effective Tax Rate by Jurisdiction",
    684: "Top-Up Tax Calculator",
    685: "Jurisdictional ETR Analyzer",
    686: "Covered Tax Analyzer",
    687: "GloBE Income Analyzer",
    688: "Entity Classification Tool",
    689: "Global Tax Data Reconciliation",
    690: "Global Minimum Tax Dashboard",
    691: "E-Invoice Requirement Checker",
    692: "Country E-Invoice Mandate Finder",
    693: "E-Invoice Schema Validator",
    694: "Invoice XML Validator",
    695: "Peppol Invoice Validator",
    696: "Invoice Tax Validator",
    697: "Country Invoice Requirement Checker",
    698: "B2B E-Invoice Checker",
    699: "B2C E-Invoice Checker",
    700: "Government Invoice Checker",
    701: "E-Invoice Format Converter",
    702: "E-Invoice Compliance Checker",
    703: "Invoice Archive Validator",
    704: "E-Invoice Country Comparator",
    705: "Global E-Invoice Dashboard",
    706: "Import Duty Calculator",
    707: "Customs Duty Calculator",
    708: "Tariff Calculator",
    709: "HS Code Search",
    710: "HS Classification Helper",
    711: "Landed Cost Calculator",
    712: "Customs Value Calculator",
    713: "Import VAT Calculator",
    714: "Import GST Calculator",
    715: "De Minimis Threshold Checker",
    716: "Preferential Tariff Checker",
    717: "Country-of-Origin Analyzer",
    718: "Free Trade Agreement Checker",
    719: "Customs Invoice Checker",
    720: "Global Import Tax Comparator",
    721: "Ecommerce Sales Tax Calculator",
    722: "Marketplace Tax Analyzer",
    723: "Seller Nexus Analyzer",
    724: "VAT OSS Analyzer",
    725: "Digital Goods Tax Calculator",
    726: "SaaS Tax Calculator",
    727: "Subscription Tax Calculator",
    728: "Marketplace Facilitator Checker",
    729: "Ecommerce VAT Registration Checker",
    730: "Ecommerce GST Registration Checker",
    731: "Cross-Border Ecommerce Tax Calculator",
    732: "Checkout Tax Calculator",
    733: "Product Taxability Analyzer",
    734: "Customer Location Tax Analyzer",
    735: "Ecommerce Tax Dashboard",
    736: "Digital Service Tax Applicability Checker",
    737: "SaaS VAT/GST Analyzer",
    738: "Digital Product Tax Analyzer",
    739: "Streaming Tax Analyzer",
    740: "Software Tax Analyzer",
    741: "Online Marketplace Tax Analyzer",
    742: "Cross-Border Digital Service Analyzer",
    743: "Customer Location Evidence Checker",
    744: "Digital Tax Threshold Checker",
    745: "Digital Tax Compliance Report",
    746: "Property Tax Calculator",
    747: "Property Transfer Tax Calculator",
    748: "Stamp Duty Calculator",
    749: "Real Estate Capital Gains Calculator",
    750: "Rental Income Tax Calculator",
    751: "Property Purchase Tax Calculator",
    752: "Property Sale Tax Calculator",
    753: "Landlord Tax Calculator",
    754: "Real Estate Tax Comparator",
    755: "Cross-Border Property Tax Analyzer",
    756: "Gift Tax Calculator",
    757: "Inheritance Tax Calculator",
    758: "Estate Tax Calculator",
    759: "Wealth Tax Calculator",
    760: "Gift Allowance Calculator",
    761: "Estate Tax Threshold Checker",
    762: "Inheritance Tax Comparator",
    763: "Cross-Border Estate Analyzer",
    764: "Gift Reporting Checker",
    765: "Estate Planning Tax Simulator",
    766: "Tax Filing Calendar",
    767: "Country Tax Calendar",
    768: "VAT Filing Calendar",
    769: "Corporate Tax Calendar",
    770: "Payroll Tax Calendar",
    771: "Withholding Calendar",
    772: "Filing Deadline Tracker",
    773: "Tax Obligation Tracker",
    774: "Tax Registration Tracker",
    775: "Tax Compliance Health Score",
    776: "Missing Filing Detector",
    777: "Late Filing Risk Analyzer",
    778: "Tax Notice Tracker",
    779: "Tax Document Manager",
    780: "Global Compliance Dashboard",
    781: "Tax Document Analyzer",
    782: "Tax Form Extractor",
    783: "Tax Notice Analyzer",
    784: "Tax Assessment Analyzer",
    785: "Tax Invoice Analyzer",
    786: "Tax Certificate Analyzer",
    787: "Withholding Certificate Analyzer",
    788: "Payroll Tax Document Analyzer",
    789: "Tax Return Compare",
    790: "Tax Return Reconciliation",
    791: "Tax Document Difference Finder",
    792: "Tax Data Extractor",
    793: "Tax PDF to Structured Data",
    794: "Tax Working Paper Generator",
    795: "Tax Documentation Report",
    796: "Tax Audit Tool",
    797: "Tax Risk Analyzer",
    798: "Tax Transaction Reconciler",
    799: "Tax Ledger Reconciliation",
    800: "Tax Return vs Books Comparator",
    801: "VAT Return vs Ledger",
    802: "GST Return vs Ledger",
    803: "Payroll Tax Reconciliation",
    804: "Withholding Reconciliation",
    805: "Corporate Tax Reconciliation",
    806: "Tax Provision Reconciliation",
    807: "Intercompany Tax Reconciliation",
    808: "Missing Transaction Detector",
    809: "Duplicate Tax Detector",
    810: "Tax Audit Dashboard",
    811: "Tax Scenario Calculator",
    812: "Tax Regime Comparator",
    813: "Country Tax Comparator",
    814: "Business Location Tax Comparator",
    815: "Employee Location Tax Comparator",
    816: "Salary Tax Scenario Planner",
    817: "Investment Tax Scenario Planner",
    818: "Corporate Structure Tax Simulator",
    819: "Cross-Border Transaction Simulator",
    820: "Tax Forecast Engine",
    821: "Tax Provision Forecast",
    822: "Tax Cash Flow Forecast",
    823: "Tax Sensitivity Analyzer",
    824: "What-If Tax Simulator",
    825: "Tax Planning Dashboard",
    826: "Automated Tax Calculator",
    827: "Automated Tax Classification",
    828: "Automated Income Classification",
    829: "Automated Transaction Tax Analyzer",
    830: "Automated GST Reconciliation",
    831: "Automated VAT Reconciliation",
    832: "Automated TDS Reconciliation",
    833: "Automated Tax Return Preparation",
    834: "Automated Tax Provision",
    835: "Automated Tax Audit",
    836: "Automated Compliance Checker",
    837: "Automated Invoice Tax Validator",
    838: "Automated Tax Calendar",
    839: "Automated Tax Documentation",
    840: "Automated Tax Risk Analyzer",
    841: "Automated Tax Notice Analyzer",
    842: "Automated Filing Readiness",
    843: "Automated Cross-Border Tax Analyzer",
    844: "Automated Tax Reporting",
    845: "Complete Tax Automation Platform",
}
