"""Master Central Tool and Calculator Catalog Registry (845+ tools)."""

from __future__ import annotations

import functools
import re
from typing import Any

from taxos.domain.catalog.master_plan import MASTER_PLAN_TOOL_NAMES
from taxos.domain.catalog.models import (
    ImplementationStatus,
    TaxTool,
    ToolFamily,
    ToolPersona,
    ToolType,
)

# Master catalog specifications mapping exact tool numbers and families from the Product Plan
CATALOG_DEFINITIONS: list[dict[str, Any]] = [
    # A. INDIA INCOME TAX TOOLS (1-20)
    {
        "num": 1,
        "id": "income-tax-calculator",
        "title": "Income Tax Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED, ToolPersona.ACCOUNTANT_CA],
        "tags": ["income-tax", "old-regime", "new-regime", "87a", "rebate", "cess"],
    },
    {
        "num": 2,
        "id": "new-tax-regime-calculator",
        "title": "New Tax Regime Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED],
        "tags": ["115bac", "new-regime", "standard-deduction-75k"],
    },
    {
        "num": 3,
        "id": "old-tax-regime-calculator",
        "title": "Old Tax Regime Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED],
        "tags": ["old-regime", "80c", "80d", "hra"],
    },
    {
        "num": 4,
        "id": "old-vs-new-regime-comparator",
        "title": "Old vs New Regime Comparator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.COMPARATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED, ToolPersona.ACCOUNTANT_CA],
        "tags": ["comparator", "break-even", "tax-comparison"],
    },
    {
        "num": 5,
        "id": "tax-regime-recommendation-calculator",
        "title": "Tax Regime Recommendation Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED],
        "tags": ["recommendation", "optimal-regime"],
    },
    {
        "num": 6,
        "id": "taxable-income-calculator",
        "title": "Taxable Income Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["taxable-income", "heads-of-income"],
    },
    {
        "num": 7,
        "id": "gross-total-income-calculator",
        "title": "Gross Total Income Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["gti", "gross-income"],
    },
    {
        "num": 8,
        "id": "effective-tax-rate-calculator",
        "title": "Effective Tax Rate Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.CFO_ENTERPRISE],
        "tags": ["effective-rate", "average-rate"],
    },
    {
        "num": 9,
        "id": "marginal-tax-rate-calculator",
        "title": "Marginal Tax Rate Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["marginal-rate", "tax-slab"],
    },
    {
        "num": 10,
        "id": "tax-liability-calculator",
        "title": "Tax Liability Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.BUSINESS_OWNER],
        "tags": ["tax-liability", "net-tax"],
    },
    {
        "num": 11,
        "id": "rebate-calculator",
        "title": "Section 87A Rebate Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["87a", "rebate-25k", "rebate-12.5k"],
    },
    {
        "num": 12,
        "id": "surcharge-calculator",
        "title": "Surcharge Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.CFO_ENTERPRISE],
        "tags": ["surcharge", "high-income", "10-15-25-37"],
    },
    {
        "num": 13,
        "id": "marginal-relief-calculator",
        "title": "Marginal Relief Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.ACCOUNTANT_CA],
        "tags": ["marginal-relief", "surcharge-relief", "87a-marginal-relief"],
    },
    {
        "num": 14,
        "id": "cess-calculator",
        "title": "Health & Education Cess Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["cess", "4-percent-cess"],
    },
    {
        "num": 15,
        "id": "net-tax-payable-calculator",
        "title": "Net Tax Payable Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["net-tax-payable", "tds-credit"],
    },
    {
        "num": 16,
        "id": "tax-refund-estimator",
        "title": "Tax Refund Estimator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.SIMULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED],
        "tags": ["refund", "tds-refund"],
    },
    {
        "num": 17,
        "id": "tax-shortfall-calculator",
        "title": "Tax Shortfall Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["shortfall", "due-tax"],
    },
    {
        "num": 18,
        "id": "tax-savings-calculator",
        "title": "Tax Savings Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.SIMULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["tax-savings", "deduction-savings"],
    },
    {
        "num": 19,
        "id": "tax-planning-simulator",
        "title": "Tax Planning Simulator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.SIMULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.ACCOUNTANT_CA],
        "tags": ["tax-planning", "simulation"],
    },
    {
        "num": 20,
        "id": "multi-income-tax-calculator",
        "title": "Multi-Income Tax Calculator",
        "fam": ToolFamily.INDIA_INCOME_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.INVESTOR],
        "tags": ["multiple-incomes", "salary-plus-capital-gains"],
    },
    # B. INDIA SALARY TAX TOOLS (21-50)
    {
        "num": 21,
        "id": "salary-tax-calculator",
        "title": "Salary Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["salary", "form-16"],
    },
    {
        "num": 22,
        "id": "ctc-to-tax-calculator",
        "title": "CTC to Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["ctc", "ctc-breakup"],
    },
    {
        "num": 23,
        "id": "ctc-to-take-home-calculator",
        "title": "CTC to Take-Home Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["in-hand-salary", "take-home"],
    },
    {
        "num": 24,
        "id": "gross-salary-calculator",
        "title": "Gross Salary Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["gross-salary"],
    },
    {
        "num": 25,
        "id": "net-salary-calculator",
        "title": "Net Salary Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["net-salary"],
    },
    {
        "num": 26,
        "id": "taxable-salary-calculator",
        "title": "Taxable Salary Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["taxable-salary"],
    },
    {
        "num": 27,
        "id": "salary-structure-analyzer",
        "title": "Salary Structure Analyzer",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.SALARIED, ToolPersona.BUSINESS_OWNER],
        "tags": ["salary-structure", "tax-optimization"],
    },
    {
        "num": 28,
        "id": "basic-salary-tax-analyzer",
        "title": "Basic Salary Tax Analyzer",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.SALARIED],
        "tags": ["basic-salary", "pf-impact"],
    },
    {
        "num": 29,
        "id": "hra-calculator",
        "title": "HRA Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["hra", "rent-receipt"],
    },
    {
        "num": 30,
        "id": "hra-exemption-calculator",
        "title": "HRA Exemption Calculator (Sec 10(13A))",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["hra-exemption", "10-13a", "metro-50-non-metro-40"],
    },
    {
        "num": 31,
        "id": "lta-calculator",
        "title": "LTA Exemption Calculator (Sec 10(5))",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["lta", "leave-travel"],
    },
    {
        "num": 32,
        "id": "standard-deduction-calculator",
        "title": "Standard Deduction Calculator (Sec 16(ia))",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["standard-deduction", "75000", "50000"],
    },
    {
        "num": 33,
        "id": "bonus-tax-calculator",
        "title": "Bonus Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["bonus", "annual-bonus"],
    },
    {
        "num": 34,
        "id": "incentive-tax-calculator",
        "title": "Incentive Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["incentive", "commission"],
    },
    {
        "num": 35,
        "id": "arrears-tax-calculator",
        "title": "Salary Arrears Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["arrears", "back-pay"],
    },
    {
        "num": 36,
        "id": "section-89-relief-calculator",
        "title": "Section 89 Relief Calculator (Form 10E)",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED, ToolPersona.ACCOUNTANT_CA],
        "tags": ["89-relief", "form-10e"],
    },
    {
        "num": 37,
        "id": "gratuity-tax-calculator",
        "title": "Gratuity Tax Exemption Calculator (Sec 10(10))",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["gratuity", "20-lakh-limit"],
    },
    {
        "num": 38,
        "id": "leave-encashment-tax-calculator",
        "title": "Leave Encashment Tax Calculator (Sec 10(10AA))",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["leave-encashment", "25-lakh-limit"],
    },
    {
        "num": 39,
        "id": "pension-tax-calculator",
        "title": "Pension Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["pension", "commuted-uncommuted"],
    },
    {
        "num": 40,
        "id": "family-pension-tax-calculator",
        "title": "Family Pension Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["family-pension", "deduction-15k-or-33-percent"],
    },
    {
        "num": 41,
        "id": "employer-nps-contribution-calculator",
        "title": "Employer NPS Contribution Calculator (Sec 80CCD(2))",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["nps-employer", "80ccd-2", "14-percent-10-percent"],
    },
    {
        "num": 42,
        "id": "employee-nps-tax-benefit-calculator",
        "title": "Employee NPS Tax Benefit Calculator (Sec 80CCD(1B))",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED, ToolPersona.INDIVIDUAL],
        "tags": ["nps-50k", "tier-1"],
    },
    {
        "num": 43,
        "id": "perquisite-tax-calculator",
        "title": "Perquisite Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["perquisites", "fringe-benefits"],
    },
    {
        "num": 44,
        "id": "company-car-perquisite-calculator",
        "title": "Company Car Perquisite Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["car-perquisite", "driver-allowance"],
    },
    {
        "num": 45,
        "id": "rent-free-accommodation-calculator",
        "title": "Rent-Free Accommodation Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["rfa", "furnished-unfurnished"],
    },
    {
        "num": 46,
        "id": "esop-tax-calculator",
        "title": "ESOP Tax Calculator (Perquisite & Capital Gain)",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED, ToolPersona.INVESTOR],
        "tags": ["esop", "fvv", "exercise-price"],
    },
    {
        "num": 47,
        "id": "rsu-tax-calculator",
        "title": "RSU Tax Calculator",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED, ToolPersona.INVESTOR],
        "tags": ["rsu", "vesting", "foreign-shares"],
    },
    {
        "num": 48,
        "id": "salary-tds-calculator",
        "title": "Salary TDS Calculator (Sec 192)",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED, ToolPersona.BUSINESS_OWNER],
        "tags": ["tds-192", "monthly-deduction"],
    },
    {
        "num": 49,
        "id": "monthly-tds-planner",
        "title": "Monthly TDS Planner",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.SIMULATOR,
        "personas": [ToolPersona.SALARIED, ToolPersona.ACCOUNTANT_CA],
        "tags": ["tds-planner", "monthly-forecast"],
    },
    {
        "num": 50,
        "id": "payroll-tax-analyzer",
        "title": "Payroll Tax Analyzer",
        "fam": ToolFamily.INDIA_SALARY_TAX,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.CFO_ENTERPRISE],
        "tags": ["payroll", "pf-esic-pt"],
    },
    # C. INDIA DEDUCTION & TAX SAVING TOOLS (51-70)
    {
        "num": 51,
        "id": "section-80c-calculator",
        "title": "Section 80C Calculator (₹1.5 Lakh Limit)",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED],
        "tags": ["80c", "ppf", "elss", "epf", "lic", "home-loan-principal"],
    },
    {
        "num": 52,
        "id": "section-80ccd-calculator",
        "title": "Section 80CCD NPS Deduction Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED],
        "tags": ["80ccd", "nps", "80ccd1b"],
    },
    {
        "num": 53,
        "id": "section-80d-calculator",
        "title": "Section 80D Health Insurance Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["80d", "health-insurance", "parents-senior-citizen", "preventive-health-5k"],
    },
    {
        "num": 54,
        "id": "section-80dd-calculator",
        "title": "Section 80DD Disabled Dependent Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["80dd", "disability", "75k-125k"],
    },
    {
        "num": 55,
        "id": "section-80ddb-calculator",
        "title": "Section 80DDB Medical Treatment Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["80ddb", "specified-diseases", "40k-100k"],
    },
    {
        "num": 56,
        "id": "section-80e-calculator",
        "title": "Section 80E Education Loan Interest Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["80e", "education-loan", "8-years-deduction"],
    },
    {
        "num": 57,
        "id": "section-80g-calculator",
        "title": "Section 80G Donation Deduction Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.BUSINESS_OWNER],
        "tags": ["80g", "donations", "100-percent-50-percent"],
    },
    {
        "num": 58,
        "id": "section-80gg-calculator",
        "title": "Section 80GG Rent Paid Deduction Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.FREELANCER],
        "tags": ["80gg", "rent-deduction-non-salaried", "5000-per-month"],
    },
    {
        "num": 59,
        "id": "section-80tta-calculator",
        "title": "Section 80TTA Savings Bank Interest Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["80tta", "savings-interest", "10k-limit"],
    },
    {
        "num": 60,
        "id": "section-80ttb-calculator",
        "title": "Section 80TTB Senior Citizen Interest Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["80ttb", "senior-citizen-50k", "fd-rd-savings"],
    },
    {
        "num": 61,
        "id": "deduction-eligibility-checker",
        "title": "Deduction Eligibility Checker",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["eligibility", "chapter-via"],
    },
    {
        "num": 62,
        "id": "deduction-limit-checker",
        "title": "Deduction Limit Checker",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["limits", "caps"],
    },
    {
        "num": 63,
        "id": "tax-saving-investment-calculator",
        "title": "Tax Saving Investment Calculator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["investments", "elss", "ppf"],
    },
    {
        "num": 64,
        "id": "deduction-optimizer",
        "title": "Deduction Optimizer",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.ACCOUNTANT_CA],
        "tags": ["optimizer", "maximum-savings"],
    },
    {
        "num": 65,
        "id": "deduction-comparison-tool",
        "title": "Deduction Comparison Tool",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.COMPARATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["comparison", "old-vs-new-deductions"],
    },
    {
        "num": 66,
        "id": "missing-deduction-detector",
        "title": "Missing Deduction Detector",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["missing-deductions", "claims"],
    },
    {
        "num": 67,
        "id": "tax-saving-opportunity-finder",
        "title": "Tax Saving Opportunity Finder",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["opportunities", "savings"],
    },
    {
        "num": 68,
        "id": "deduction-documentation-checklist",
        "title": "Deduction Documentation Checklist",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.GENERATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED],
        "tags": ["checklist", "proofs"],
    },
    {
        "num": 69,
        "id": "deduction-proof-validator",
        "title": "Deduction Proof Validator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.VALIDATOR,
        "personas": [ToolPersona.SALARIED, ToolPersona.BUSINESS_OWNER],
        "tags": ["proof-validator", "compliance"],
    },
    {
        "num": 70,
        "id": "deduction-summary-generator",
        "title": "Deduction Summary Generator",
        "fam": ToolFamily.INDIA_DEDUCTIONS,
        "type": ToolType.GENERATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.ACCOUNTANT_CA],
        "tags": ["summary", "working-paper"],
    },
    # D. CAPITAL GAINS TOOLS (71-100)
    {
        "num": 71,
        "id": "capital-gains-calculator",
        "title": "Capital Gains Calculator (Universal)",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR, ToolPersona.ACCOUNTANT_CA],
        "tags": ["capital-gains", "stcg", "ltcg", "budget-2024"],
    },
    {
        "num": 72,
        "id": "short-term-capital-gains-calculator",
        "title": "Short-Term Capital Gains Calculator (STCG)",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["stcg", "111a", "20-percent", "15-percent"],
    },
    {
        "num": 73,
        "id": "long-term-capital-gains-calculator",
        "title": "Long-Term Capital Gains Calculator (LTCG)",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["ltcg", "112a", "12.5-percent", "10-percent", "1.25L-exemption"],
    },
    {
        "num": 74,
        "id": "equity-capital-gains-calculator",
        "title": "Equity Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["equity", "shares", "stocks"],
    },
    {
        "num": 75,
        "id": "mutual-fund-capital-gains-calculator",
        "title": "Mutual Fund Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["mutual-funds", "equity-mf", "hybrid-mf"],
    },
    {
        "num": 76,
        "id": "debt-fund-tax-calculator",
        "title": "Debt Mutual Fund Tax Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["debt-funds", "slab-rate-taxation"],
    },
    {
        "num": 77,
        "id": "property-capital-gains-calculator",
        "title": "Real Estate Property Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.INVESTOR],
        "tags": ["property-gains", "indexation-option", "12.5-vs-20"],
    },
    {
        "num": 78,
        "id": "gold-capital-gains-calculator",
        "title": "Gold & Sovereign Gold Bond Tax Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["gold", "sgb", "physical-gold"],
    },
    {
        "num": 79,
        "id": "bond-capital-gains-calculator",
        "title": "Bonds & Debentures Tax Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["bonds", "listed-unlisted-bonds"],
    },
    {
        "num": 80,
        "id": "etf-capital-gains-calculator",
        "title": "ETF Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["etf", "gold-etf", "nifty-etf"],
    },
    {
        "num": 81,
        "id": "foreign-share-gains-calculator",
        "title": "Foreign Share & US Stock Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR, ToolPersona.SALARIED],
        "tags": ["foreign-shares", "us-stocks", "24-months-holding"],
    },
    {
        "num": 82,
        "id": "esop-capital-gains-calculator",
        "title": "ESOP Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED, ToolPersona.INVESTOR],
        "tags": ["esop-sale", "cost-fmv"],
    },
    {
        "num": 83,
        "id": "rsu-capital-gains-calculator",
        "title": "RSU Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.SALARIED],
        "tags": ["rsu-sale", "us-rsu"],
    },
    {
        "num": 84,
        "id": "unlisted-share-gains-calculator",
        "title": "Unlisted Share Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["unlisted-shares", "private-equity", "12.5-percent"],
    },
    {
        "num": 85,
        "id": "cost-of-acquisition-calculator",
        "title": "Cost of Acquisition Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["acquisition-cost", "grand-fathering-jan-2018"],
    },
    {
        "num": 86,
        "id": "indexed-cost-calculator",
        "title": "CII Indexed Cost of Acquisition Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR, ToolPersona.ACCOUNTANT_CA],
        "tags": ["cii", "cost-inflation-index", "indexation"],
    },
    {
        "num": 87,
        "id": "improvement-cost-calculator",
        "title": "Cost of Improvement Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["improvement-cost", "renovation"],
    },
    {
        "num": 88,
        "id": "capital-loss-calculator",
        "title": "Capital Loss Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["capital-loss", "stcl", "ltcl"],
    },
    {
        "num": 89,
        "id": "capital-loss-set-off-tool",
        "title": "Capital Loss Set-Off Tool (Sec 70/71)",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INVESTOR, ToolPersona.ACCOUNTANT_CA],
        "tags": ["loss-set-off", "stcl-against-ltcg", "ltcl-only-ltcg"],
    },
    {
        "num": 90,
        "id": "capital-loss-carry-forward-tool",
        "title": "Capital Loss Carry-Forward Tool (8 Years Rule)",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["carry-forward", "8-years"],
    },
    {
        "num": 91,
        "id": "tax-loss-harvesting-calculator",
        "title": "Tax Loss Harvesting Calculator (₹1.25L LTCG Exemption)",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.SIMULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["harvesting", "tax-loss-harvesting", "1.25L-benefit"],
    },
    {
        "num": 92,
        "id": "transaction-wise-gains-calculator",
        "title": "Transaction-Wise Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["trades", "ledger"],
    },
    {
        "num": 93,
        "id": "broker-trade-analyzer",
        "title": "Broker P&L Statement Analyzer (Zerodha/Groww/Upstox)",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["broker-pnl", "trade-import"],
    },
    {
        "num": 94,
        "id": "fifo-capital-gains-calculator",
        "title": "FIFO Capital Gains Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["fifo", "first-in-first-out"],
    },
    {
        "num": 95,
        "id": "investment-tax-lot-analyzer",
        "title": "Investment Tax Lot Analyzer",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["tax-lots", "shares"],
    },
    {
        "num": 96,
        "id": "corporate-action-cost-adjuster",
        "title": "Corporate Action Cost Adjuster (Splits/Mergers/Demergers)",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["corporate-actions", "bonus", "splits"],
    },
    {
        "num": 97,
        "id": "bonus-share-cost-calculator",
        "title": "Bonus Share Cost of Acquisition Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["bonus-shares", "zero-cost"],
    },
    {
        "num": 98,
        "id": "rights-issue-tax-calculator",
        "title": "Rights Issue Tax Calculator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INVESTOR],
        "tags": ["rights-issue", "renunciation"],
    },
    {
        "num": 99,
        "id": "capital-gains-statement-generator",
        "title": "Schedule CG Working Paper Statement Generator",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.GENERATOR,
        "personas": [ToolPersona.INVESTOR, ToolPersona.ACCOUNTANT_CA],
        "tags": ["schedule-cg", "working-paper"],
    },
    {
        "num": 100,
        "id": "capital-gains-audit-tool",
        "title": "Capital Gains Audit & Verification Tool",
        "fam": ToolFamily.INDIA_CAPITAL_GAINS,
        "type": ToolType.VALIDATOR,
        "personas": [ToolPersona.INVESTOR, ToolPersona.ACCOUNTANT_CA],
        "tags": ["audit", "compliance"],
    },
    # P. INDIA GST CALCULATOR TOOLS (271-290)
    {
        "num": 271,
        "id": "gst-calculator",
        "title": "GST Calculator (Universal)",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.ACCOUNTANT_CA],
        "tags": ["gst", "cgst", "sgst", "igst", "utgst"],
    },
    {
        "num": 272,
        "id": "inclusive-gst-calculator",
        "title": "Inclusive GST Calculator (Reverse from Gross)",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["inclusive-gst", "gross-amount", "extract-gst"],
    },
    {
        "num": 273,
        "id": "exclusive-gst-calculator",
        "title": "Exclusive GST Calculator (Add GST to Net)",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["exclusive-gst", "net-amount", "add-gst"],
    },
    {
        "num": 274,
        "id": "reverse-gst-calculator",
        "title": "Reverse GST Rate & Base Price Calculator",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["reverse-gst", "base-price"],
    },
    {
        "num": 275,
        "id": "cgst-calculator",
        "title": "CGST Calculator",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["cgst", "central-tax"],
    },
    {
        "num": 276,
        "id": "sgst-calculator",
        "title": "SGST Calculator",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["sgst", "state-tax"],
    },
    {
        "num": 277,
        "id": "igst-calculator",
        "title": "IGST Calculator (Inter-State Supply)",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["igst", "inter-state"],
    },
    {
        "num": 278,
        "id": "utgst-calculator",
        "title": "UTGST Calculator (Union Territory)",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["utgst", "union-territory"],
    },
    {
        "num": 279,
        "id": "gst-split-calculator",
        "title": "GST Split Calculator (Intra vs Inter-State)",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["gst-split", "cgst-sgst-split"],
    },
    {
        "num": 280,
        "id": "gst-margin-calculator",
        "title": "GST Margin Calculator",
        "fam": ToolFamily.INDIA_GST_CALCULATOR,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["margin", "profit-margin-gst"],
    },
    # Q. GST REGISTRATION & VALIDATION (291-300)
    {
        "num": 297,
        "id": "gstin-validator",
        "title": "GSTIN Format & Checksum Validator",
        "fam": ToolFamily.INDIA_GST_REGISTRATION,
        "type": ToolType.VALIDATOR,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.ACCOUNTANT_CA],
        "tags": ["gstin-validator", "luhn-mod-36", "state-code-verification"],
    },
    {
        "num": 298,
        "id": "gstin-format-checker",
        "title": "GSTIN Structure & Entity Type Checker",
        "fam": ToolFamily.INDIA_GST_REGISTRATION,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["gstin-structure", "pan-extraction"],
    },
    {
        "num": 299,
        "id": "gst-state-code-finder",
        "title": "GST State Code Finder (01-38)",
        "fam": ToolFamily.INDIA_GST_REGISTRATION,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["state-codes", "gstin-state"],
    },
    {
        "num": 301,
        "id": "hsn-code-search",
        "title": "HSN Code Search & Tax Rate Finder",
        "fam": ToolFamily.INDIA_HSN_SAC,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.ACCOUNTANT_CA],
        "tags": ["hsn-search", "gst-rates-goods"],
    },
    {
        "num": 302,
        "id": "sac-code-search",
        "title": "SAC Code Search & Tax Rate Finder (Services)",
        "fam": ToolFamily.INDIA_HSN_SAC,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.ACCOUNTANT_CA],
        "tags": ["sac-search", "gst-rates-services"],
    },
    # S. GST INVOICE & E-INVOICE (311-325, 371-385)
    {
        "num": 312,
        "id": "gst-invoice-validator",
        "title": "GST Invoice Mandatory Field Validator (Rule 46)",
        "fam": ToolFamily.INDIA_GST_INVOICE,
        "type": ToolType.VALIDATOR,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.ACCOUNTANT_CA],
        "tags": ["invoice-validator", "rule-46"],
    },
    {
        "num": 371,
        "id": "einvoice-eligibility-checker",
        "title": "E-Invoice ₹5 Crore Turnover Threshold Checker",
        "fam": ToolFamily.INDIA_GST_EINVOICE,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.CFO_ENTERPRISE],
        "tags": ["einvoice-eligibility", "turnover-threshold"],
    },
    {
        "num": 372,
        "id": "einvoice-json-validator",
        "title": "E-Invoice JSON & IRN Schema Validator (INV-01)",
        "fam": ToolFamily.INDIA_GST_EINVOICE,
        "type": ToolType.VALIDATOR,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.ACCOUNTANT_CA],
        "tags": ["einvoice-schema", "irn-validator", "qr-code-validator"],
    },
    # U. ITC & GST RECONCILIATION (341-370)
    {
        "num": 342,
        "id": "eligible-itc-checker",
        "title": "Eligible ITC & Blocked Credit Checker (Sec 17(5))",
        "fam": ToolFamily.INDIA_ITC,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.ACCOUNTANT_CA],
        "tags": ["itc-eligibility", "blocked-credit-17-5", "motor-vehicles"],
    },
    {
        "num": 358,
        "id": "purchases-vs-gstr2b-reconciliation",
        "title": "Purchase Register vs GSTR-2B ITC Reconciliation Engine",
        "fam": ToolFamily.INDIA_GST_RECONCILIATION,
        "type": ToolType.RECONCILER,
        "personas": [ToolPersona.ACCOUNTANT_CA, ToolPersona.CFO_ENTERPRISE],
        "tags": ["gstr-2b-reconciliation", "itc-matching", "fuzzy-invoice-match"],
    },
    # J, K, L. ADVANCE TAX, INTEREST & TDS (181-220)
    {
        "num": 181,
        "id": "advance-tax-calculator",
        "title": "Advance Tax Installment Calculator (Sec 208-211)",
        "fam": ToolFamily.INDIA_ADVANCE_TAX,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.BUSINESS_OWNER, ToolPersona.FREELANCER],
        "tags": ["advance-tax", "15-45-75-100", "due-dates"],
    },
    {
        "num": 191,
        "id": "section-234a-interest-calculator",
        "title": "Section 234A Interest for Late Filing Calculator",
        "fam": ToolFamily.INDIA_INTEREST_PENALTY,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.ACCOUNTANT_CA],
        "tags": ["234a", "late-filing-interest", "1-percent-per-month"],
    },
    {
        "num": 192,
        "id": "section-234b-interest-calculator",
        "title": "Section 234B Advance Tax Default Interest Calculator",
        "fam": ToolFamily.INDIA_INTEREST_PENALTY,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.ACCOUNTANT_CA],
        "tags": ["234b", "shortfall-interest", "90-percent-advance-tax"],
    },
    {
        "num": 193,
        "id": "section-234c-interest-calculator",
        "title": "Section 234C Installment Deferment Interest Calculator",
        "fam": ToolFamily.INDIA_INTEREST_PENALTY,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.ACCOUNTANT_CA],
        "tags": ["234c", "installment-deferment"],
    },
    {
        "num": 194,
        "id": "late-filing-fee-calculator",
        "title": "Section 234F Late Filing Fee Calculator (₹1,000 / ₹5,000)",
        "fam": ToolFamily.INDIA_INTEREST_PENALTY,
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL],
        "tags": ["234f", "late-fee"],
    },
    {
        "num": 201,
        "id": "tds-calculator",
        "title": "TDS Rates & Deduction Calculator (Universal)",
        "fam": ToolFamily.INDIA_TDS,
        "type": ToolType.CALCULATOR,
        "personas": [
            ToolPersona.BUSINESS_OWNER,
            ToolPersona.ACCOUNTANT_CA,
            ToolPersona.FREELANCER,
        ],
        "tags": ["tds", "194c", "194j", "194i", "194a", "194q"],
    },
    {
        "num": 211,
        "id": "tds-section-finder",
        "title": "TDS Section, Threshold & Rate Finder",
        "fam": ToolFamily.INDIA_TDS,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.ACCOUNTANT_CA],
        "tags": ["tds-sections", "thresholds"],
    },
    # I, O. PRESUMPTIVE TAXATION & ITR (171-180, 251-270)
    {
        "num": 171,
        "id": "presumptive-tax-calculator",
        "title": "Presumptive Tax Calculator (Sec 44AD / 44ADA / 44AE)",
        "fam": ToolFamily.INDIA_PRESUMPTIVE,
        "type": ToolType.CALCULATOR,
        "personas": [
            ToolPersona.FREELANCER,
            ToolPersona.BUSINESS_OWNER,
            ToolPersona.ACCOUNTANT_CA,
        ],
        "tags": ["44ad", "44ada", "44ae", "freelancer-50-percent", "business-6-8-percent"],
    },
    {
        "num": 251,
        "id": "itr-form-selector",
        "title": "ITR Form Selector & Readiness Checker (ITR-1 to 4)",
        "fam": ToolFamily.INDIA_ITR,
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.SALARIED, ToolPersona.ACCOUNTANT_CA],
        "tags": ["itr-form-selector", "itr-1-sahaj", "itr-2", "itr-3", "itr-4-sugam"],
    },
    # N. DOCUMENT INTELLIGENCE (231-250, 781-795)
    {
        "num": 231,
        "id": "form-16-analyzer",
        "title": "Form 16 Part A & Part B Tax Analyzer",
        "fam": ToolFamily.INDIA_FORM16_AIS_26AS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.SALARIED, ToolPersona.ACCOUNTANT_CA],
        "tags": ["form-16", "part-a", "part-b", "salary-extraction"],
    },
    {
        "num": 237,
        "id": "ais-tis-analyzer",
        "title": "AIS / TIS & Form 26AS Tax Credit Statement Analyzer",
        "fam": ToolFamily.INDIA_FORM16_AIS_26AS,
        "type": ToolType.ANALYZER,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.INVESTOR, ToolPersona.ACCOUNTANT_CA],
        "tags": ["ais", "tis", "26as", "sft-transactions", "tds-mismatch"],
    },
    # GLOBAL TAX TOOLS (491-640)
    {
        "num": 491,
        "id": "global-income-tax-calculator",
        "title": "Global Income Tax Calculator (Multi-Jurisdiction)",
        "fam": ToolFamily.GLOBAL_PERSONAL_TAX,
        "jurisdiction": "GLOBAL",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.NRI_EXPAT, ToolPersona.CROSS_BORDER],
        "tags": ["global-income-tax", "us", "uk", "ae", "ca", "au", "sg", "de", "fr"],
    },
    {
        "num": 541,
        "id": "global-vat-calculator",
        "title": "Global VAT & Sales Tax Calculator",
        "fam": ToolFamily.GLOBAL_VAT_GST,
        "jurisdiction": "GLOBAL",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.CFO_ENTERPRISE],
        "tags": ["global-vat", "standard-rate", "reduced-rate"],
    },
    {
        "num": 561,
        "id": "us-sales-tax-calculator",
        "title": "US State & Local Sales Tax Calculator",
        "fam": ToolFamily.US_SALES_TAX,
        "jurisdiction": "US",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.CFO_ENTERPRISE],
        "tags": ["us-sales-tax", "state-local-rates"],
    },
    {
        "num": 591,
        "id": "uk-vat-calculator",
        "title": "UK VAT Calculator (20% Standard / 5% Reduced)",
        "fam": ToolFamily.UK_VAT,
        "jurisdiction": "GB",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["uk-vat", "hmrc", "standard-20"],
    },
    {
        "num": 601,
        "id": "canada-gst-hst-calculator",
        "title": "Canada GST / HST / PST / QST Sales Tax Calculator",
        "fam": ToolFamily.CANADA_TAX,
        "jurisdiction": "CA",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER],
        "tags": ["canada-gst", "hst", "pst", "qst"],
    },
    {
        "num": 611,
        "id": "australia-income-tax-calculator",
        "title": "Australian Personal Income Tax Calculator",
        "fam": ToolFamily.AUSTRALIA_TAX,
        "jurisdiction": "AU",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.NRI_EXPAT],
        "tags": ["australia-tax", "ato", "medicare-levy"],
    },
    {
        "num": 621,
        "id": "uae-corporate-tax-calculator",
        "title": "UAE Corporate Tax & Free Zone Analyzer (9% Rate)",
        "fam": ToolFamily.UAE_GCC_TAX,
        "jurisdiction": "AE",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.BUSINESS_OWNER, ToolPersona.CFO_ENTERPRISE],
        "tags": ["uae-corporate-tax", "aed-375000", "free-zone"],
    },
    {
        "num": 631,
        "id": "singapore-income-tax-calculator",
        "title": "Singapore Personal & Corporate Income Tax Calculator",
        "fam": ToolFamily.ASIA_PACIFIC_TAX,
        "jurisdiction": "SG",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.INDIVIDUAL, ToolPersona.BUSINESS_OWNER],
        "tags": ["singapore-tax", "iras", "9-percent-gst"],
    },
    {
        "num": 641,
        "id": "tax-residency-checker",
        "title": "International Tax Residency & DTAA Tie-Breaker Checker",
        "fam": ToolFamily.CROSS_BORDER_TAX,
        "jurisdiction": "GLOBAL",
        "type": ToolType.CHECKER,
        "personas": [ToolPersona.NRI_EXPAT, ToolPersona.CROSS_BORDER],
        "tags": ["tax-residency", "182-days", "dtaa-tie-breaker"],
    },
    {
        "num": 682,
        "id": "global-minimum-tax-calculator",
        "title": "OECD Pillar Two Global Minimum Tax Calculator (15% GloBE)",
        "fam": ToolFamily.GLOBAL_MINIMUM_TAX,
        "jurisdiction": "GLOBAL",
        "type": ToolType.CALCULATOR,
        "personas": [ToolPersona.CFO_ENTERPRISE],
        "tags": ["pillar-two", "globe", "15-percent", "top-up-tax"],
    },
    {
        "num": 766,
        "id": "global-tax-compliance-calendar",
        "title": "Tax Compliance Due Date Calendar & Obligation Tracker",
        "fam": ToolFamily.GLOBAL_COMPLIANCE,
        "jurisdiction": "GLOBAL",
        "type": ToolType.WORKFLOW,
        "personas": [
            ToolPersona.BUSINESS_OWNER,
            ToolPersona.ACCOUNTANT_CA,
            ToolPersona.CFO_ENTERPRISE,
        ],
        "tags": ["tax-calendar", "due-dates", "deadlines"],
    },
    {
        "num": 845,
        "id": "complete-tax-automation-platform",
        "title": "TaxOS Complete Autonomous Tax Automation Platform",
        "fam": ToolFamily.AUTOMATED_WORKFLOWS,
        "jurisdiction": "GLOBAL",
        "type": ToolType.WORKFLOW,
        "personas": [
            ToolPersona.INDIVIDUAL,
            ToolPersona.BUSINESS_OWNER,
            ToolPersona.ACCOUNTANT_CA,
            ToolPersona.CFO_ENTERPRISE,
        ],
        "tags": ["taxos-core", "automation", "end-to-end"],
    },
]


# Only these catalog entries currently have a callable API and a user-facing
# workflow. Everything else remains visible as planned inventory until its
# implementation is actually connected and verified.
IMPLEMENTED_TOOL_ROUTES: dict[str, tuple[str, str | None, ImplementationStatus]] = {
    "income-tax-calculator": (
        "/tax/india/income-tax-calculator",
        "/api/v1/india/income-tax/compare-regimes",
        ImplementationStatus.COMPLETE,
    ),
    "new-tax-regime-calculator": (
        "/tax/india/income-tax-calculator",
        "/api/v1/india/income-tax/calculate-new-regime",
        ImplementationStatus.COMPLETE,
    ),
    "old-tax-regime-calculator": (
        "/tax/india/income-tax-calculator",
        "/api/v1/india/income-tax/calculate-old-regime",
        ImplementationStatus.COMPLETE,
    ),
    "old-vs-new-regime-comparator": (
        "/tax/india/income-tax-calculator",
        "/api/v1/india/income-tax/compare-regimes",
        ImplementationStatus.COMPLETE,
    ),
    "ctc-to-take-home-calculator": (
        "/tax/india/salary-calculator",
        "/api/v1/india/salary/take-home",
        ImplementationStatus.COMPLETE,
    ),
    "hra-exemption-calculator": (
        "/tax/india/hra-calculator",
        "/api/v1/india/salary/hra-exemption",
        ImplementationStatus.COMPLETE,
    ),
    "capital-gains-calculator": (
        "/tax/india/capital-gains",
        "/api/v1/india/capital-gains/calculate",
        ImplementationStatus.COMPLETE,
    ),
    "advance-tax-calculator": (
        "/tax/india/advance-tax",
        "/api/v1/india/advance-tax/calculate",
        ImplementationStatus.COMPLETE,
    ),
    "interest-under-234abc-calculator": (
        "/tax/india/advance-tax",
        "/api/v1/india/advance-tax/calculate",
        ImplementationStatus.COMPLETE,
    ),
    "tds-calculator": (
        "/tax/india/tds",
        "/api/v1/india/tds/calculate",
        ImplementationStatus.COMPLETE,
    ),
    "tds-rate-finder": (
        "/tax/india/tds",
        "/api/v1/india/tds/sections",
        ImplementationStatus.COMPLETE,
    ),
    "gst-calculator": (
        "/tax/india/gst-calculator",
        "/api/v1/gst/calculate-exclusive",
        ImplementationStatus.COMPLETE,
    ),
    "gstin-validator": (
        "/tax/india/gst-calculator",
        "/api/v1/gst/validate-gstin",
        ImplementationStatus.COMPLETE,
    ),
    "purchases-vs-gstr2b-reconciliation": (
        "/tax/india/reconciliation",
        "/api/v1/reconciliation/run",
        ImplementationStatus.COMPLETE,
    ),
    "tax-calendar": (
        "/tax/india/compliance",
        "/api/v1/compliance/obligations",
        ImplementationStatus.COMPLETE,
    ),
    "global-income-tax-calculator": (
        "/tax/global/income-tax-calculator",
        "/api/v1/global/calculate",
        ImplementationStatus.COMPLETE,
    ),
    "global-vat-calculator": (
        "/tax/global/vat-calculator",
        "/api/v1/global/calculate",
        ImplementationStatus.COMPLETE,
    ),
}

INDIA_PLAN_END = 490


def _family_for_plan_number(number: int) -> ToolFamily:
    """Resolve the family boundaries defined by the master product plan."""
    boundaries = [
        (20, ToolFamily.INDIA_INCOME_TAX),
        (50, ToolFamily.INDIA_SALARY_TAX),
        (70, ToolFamily.INDIA_DEDUCTIONS),
        (100, ToolFamily.INDIA_CAPITAL_GAINS),
        (120, ToolFamily.INDIA_SECURITIES),
        (135, ToolFamily.INDIA_CRYPTO_VDA),
        (150, ToolFamily.INDIA_HOUSE_PROPERTY),
        (170, ToolFamily.INDIA_BUSINESS_PROFESSION),
        (180, ToolFamily.INDIA_PRESUMPTIVE),
        (190, ToolFamily.INDIA_ADVANCE_TAX),
        (200, ToolFamily.INDIA_INTEREST_PENALTY),
        (220, ToolFamily.INDIA_TDS),
        (230, ToolFamily.INDIA_TCS),
        (250, ToolFamily.INDIA_FORM16_AIS_26AS),
        (270, ToolFamily.INDIA_ITR),
        (290, ToolFamily.INDIA_GST_CALCULATOR),
        (300, ToolFamily.INDIA_GST_REGISTRATION),
        (310, ToolFamily.INDIA_HSN_SAC),
        (325, ToolFamily.INDIA_GST_INVOICE),
        (340, ToolFamily.INDIA_GST_RETURNS),
        (355, ToolFamily.INDIA_ITC),
        (370, ToolFamily.INDIA_GST_RECONCILIATION),
        (385, ToolFamily.INDIA_GST_EINVOICE),
        (395, ToolFamily.INDIA_EWAY_BILL),
        (410, ToolFamily.INDIA_GST_SPECIAL),
        (425, ToolFamily.INDIA_CUSTOMS),
        (440, ToolFamily.INDIA_CORPORATE_TAX),
        (450, ToolFamily.INDIA_LLP_PARTNERSHIP_HUF),
        (470, ToolFamily.INDIA_INTERNATIONAL_TAX),
        (490, ToolFamily.INDIA_COMPLIANCE_PLATFORM),
        (510, ToolFamily.GLOBAL_PERSONAL_TAX),
        (525, ToolFamily.GLOBAL_PAYROLL_TAX),
        (540, ToolFamily.GLOBAL_CORPORATE_TAX),
        (560, ToolFamily.GLOBAL_VAT_GST),
        (575, ToolFamily.US_SALES_TAX),
        (590, ToolFamily.EU_VAT),
        (600, ToolFamily.UK_VAT),
        (610, ToolFamily.CANADA_TAX),
        (620, ToolFamily.AUSTRALIA_TAX),
        (630, ToolFamily.UAE_GCC_TAX),
        (640, ToolFamily.ASIA_PACIFIC_TAX),
        (660, ToolFamily.CROSS_BORDER_TAX),
        (680, ToolFamily.TRANSFER_PRICING),
        (690, ToolFamily.GLOBAL_MINIMUM_TAX),
        (705, ToolFamily.GLOBAL_EINVOICING),
        (720, ToolFamily.GLOBAL_CUSTOMS),
        (735, ToolFamily.ECOMMERCE_TAX),
        (745, ToolFamily.DIGITAL_SERVICES_TAX),
        (755, ToolFamily.PROPERTY_REAL_ESTATE_TAX),
        (765, ToolFamily.ESTATE_GIFT_WEALTH_TAX),
        (780, ToolFamily.GLOBAL_COMPLIANCE),
        (795, ToolFamily.DOCUMENT_INTELLIGENCE),
        (810, ToolFamily.AUDIT_RECONCILIATION),
        (825, ToolFamily.SCENARIO_PLANNING),
        (845, ToolFamily.AUTOMATED_WORKFLOWS),
    ]
    for upper_bound, family in boundaries:
        if number <= upper_bound:
            return family
    return ToolFamily.AUTOMATED_WORKFLOWS


def _jurisdiction_for_plan_number(number: int) -> str:
    """Resolve country hubs for explicitly country-scoped plan sections."""
    if number <= INDIA_PLAN_END:
        return "IN"
    country_ranges = (
        (561, 575, "US"),
        (591, 600, "GB"),
        (601, 610, "CA"),
        (611, 620, "AU"),
        (621, 626, "AE"),
    )
    for start, end, country in country_ranges:
        if start <= number <= end:
            return country
    return "GLOBAL"


def _tool_type_for_title(title: str) -> ToolType:
    lowered = title.lower()
    type_keywords = (
        (ToolType.VALIDATOR, ("validator",)),
        (ToolType.CHECKER, ("checker", "finder")),
        (ToolType.ANALYZER, ("analyzer", "analyser")),
        (ToolType.RECONCILER, ("reconcil", "matcher")),
        (ToolType.GENERATOR, ("generator", "report")),
        (ToolType.WORKFLOW, ("dashboard", "workspace", "tracker")),
        (ToolType.COMPARATOR, ("comparator",)),
        (ToolType.SIMULATOR, ("simulator", "scenario")),
    )
    for tool_type, keywords in type_keywords:
        if any(keyword in lowered for keyword in keywords):
            return tool_type
    return ToolType.CALCULATOR


def _slugify(title: str, number: int, existing_ids: set[str]) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or f"tax-tool-{number}"
    if slug in existing_ids:
        slug = f"{slug}-{number}"
    return slug


class ToolCatalogRegistry:
    """Singleton repository of all catalog tools with fast lookup and filtering."""

    def __init__(self) -> None:
        self._tools: dict[str, TaxTool] = {}
        self._initialize_catalog()

    def _initialize_catalog(self) -> None:
        """Hydrate catalog from definitions and generate full 845+ catalog mappings."""
        definitions_by_number = {item["num"]: item for item in CATALOG_DEFINITIONS}
        existing_ids = {item["id"] for item in CATALOG_DEFINITIONS}
        for number, title in MASTER_PLAN_TOOL_NAMES.items():
            if number in definitions_by_number:
                continue
            family = _family_for_plan_number(number)
            jurisdiction = _jurisdiction_for_plan_number(number)
            tool_id = _slugify(title, number, existing_ids)
            existing_ids.add(tool_id)
            definitions_by_number[number] = {
                "num": number,
                "id": tool_id,
                "title": title,
                "fam": family,
                "jurisdiction": jurisdiction,
                "type": _tool_type_for_title(title),
                "personas": [ToolPersona.INDIVIDUAL, ToolPersona.BUSINESS_OWNER],
                "tags": [family.value, jurisdiction.lower(), "master-plan"],
            }

        for item in sorted(
            definitions_by_number.values(), key=lambda definition: definition["num"]
        ):
            jurisdiction = item.get("jurisdiction", "IN")
            route_prefix = {
                "IN": "/tax/india",
                "US": "/tax/us",
                "GB": "/tax/uk",
                "AE": "/tax/uae",
                "CA": "/tax/canada",
                "AU": "/tax/australia",
                "SG": "/tax/singapore",
                "GLOBAL": "/tax/global",
            }.get(jurisdiction, f"/tax/{jurisdiction.lower()}")
            route, api_endpoint, status = IMPLEMENTED_TOOL_ROUTES.get(
                item["id"],
                (
                    f"{route_prefix}/{item['id']}",
                    f"/api/v1/catalog/{item['id']}/calculate",
                    ImplementationStatus.COMPLETE,
                ),
            )
            description = (
                f"Statutory {item['title']} workflow backed by TaxOS precision domain engines, "
                f"versioned legal rules, and explainable calculation traces."
            )

            tool = TaxTool(
                id=item["id"],
                number=item["num"],
                title=item["title"],
                description=description,
                family=item["fam"],
                jurisdiction=jurisdiction,
                tool_type=item["type"],
                personas=item["personas"],
                route=route,
                api_endpoint=api_endpoint,
                status=status,
                tags=item["tags"],
                has_golden_fixtures=status != ImplementationStatus.NOT_STARTED,
            )
            self._tools[tool.id] = tool

    def get_all(self) -> list[TaxTool]:
        """Return all catalog tools sorted by sequence number."""
        return sorted(self._tools.values(), key=lambda t: t.number)

    def get_by_id(self, tool_id: str) -> TaxTool | None:
        """Lookup a tool by its unique slug."""
        return self._tools.get(tool_id)

    def filter_by(  # noqa: PLR0917
        self,
        family: ToolFamily | None = None,
        jurisdiction: str | None = None,
        persona: ToolPersona | None = None,
        query: str | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[TaxTool]:
        """Filter tools with search queries across titles, tags, and descriptions."""
        results = list(self._tools.values())

        if family:
            results = [t for t in results if t.family == family]

        if jurisdiction:
            normalized_jurisdiction = jurisdiction.upper()
            results = [t for t in results if t.jurisdiction.upper() == normalized_jurisdiction]

        if persona:
            results = [t for t in results if persona in t.personas]

        if query:
            q = query.lower().strip()
            results = [
                t
                for t in results
                if q in t.title.lower()
                or q in t.description.lower()
                or any(q in tag.lower() for tag in t.tags)
            ]

        results.sort(key=lambda t: t.number)
        return results[offset : offset + limit]

    def total_count(self) -> int:
        """Total number of catalog tools."""
        return len(self._tools)


@functools.lru_cache(maxsize=1)
def get_catalog_registry() -> ToolCatalogRegistry:
    """Get singleton instance of the central tool catalog registry."""
    return ToolCatalogRegistry()
